show_empty_screen=yes
force_force_window=no
dpi_scale=1.2

accent_color="#7aa2f7"
context_menu=yes
tooltip=yes
show_mini_seekbar=yes
screenshot_button=yes
pip_button=yes
window_controls=auto
mouse_timeout=2
show_on_mouse_move=no
single_click_actions_enabled=yes
seeking_zone_percentage=3
seek_step_seconds=5
temporary_speed=2
show_remaining_time=no
adjust_time_with_speed=yes
max_volume_percentage=150
skip_intro_outro_chapters=ask
skip_intro_detection_texts=intro,introduction,opening,op,opening theme
skip_outro_detection_texts=outro,ending,end credits,credits,closing,ed
force_hwdec=yes
force_display_resample=yes
directory_playlist=yes
directory_playlist_sort=name
youtube_quality=auto
sponsorblock_should_use=yes
# SponsorBlock categories: sponsor,selfpromo,exclusive_access,interaction,intro,outro,preview,hook,music_offtopic,poi_highlight,filler
sponsorblock_auto_skip_categories=sponsor
sponsorblock_ignore_categories=interaction,preview,hook,exclusive_access
sponsorblock_multicolored_segments=yes
sponsorblock_show_submit=yes
sponsorblock_show_voting=yes
