# Options are slash-separated lists of words and languages
# These are the default settings, intended for anime

preferred_audio_lang=ja/jpn/jp
preferred_audio_channels=
excluded_audio_words=
expected_audio_words=

preferred_video_lang=
excluded_video_words=
expected_video_words=

preferred_sub_lang=ru/rus/Russian
excluded_sub_words=Forced/Надписи/надписи/Signs/signs
expected_sub_words=Full/full/Полные/полные

# Settings for selecting dubs

#preferred_audio_lang=eng
#preferred_audio_channels=
#excluded_audio_words=
#expected_audio_words=
#
#preferred_sub_lang=eng
#excluded_sub_words=
#expected_sub_words=sign
