# Window
auto_reload_config 0.1
confirm_os_window_close 0
dynamic_background_opacity yes
input_delay 0
remember_window_size no
repaint_delay 2
sync_to_monitor no
url_style curly
wayland_enable_ime no
window_padding_width 20
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
background_opacity 0.8
background_blur 1
# Scrollback
scrollback_lines 10000
wheel_scroll_multiplier 3.0
# tab_title_template "{cmdline}"
# Font
font_size 11.5
# font_family      SFMono Nerd Font Mono
font_family        JetBrainsMono Nerd Font
# font_family Ioskeley Mono
# font_family RobotoMono Nerd Font Mono
bold_font          auto 
italic_font        auto
bold_italic_font   auto

# Cursor
cursor_blink_interval 0
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.01 0.4
shell_integration no-cursor

# Mouse
mouse_hide_wait 3.0
copy_on_select clipboard
paste_actions quote-urls-at-prompt

# Selection
select_by_word_characters ,│`|:"' ()[]{}<>

# Colors — Nord
# background #2E3440
# foreground #D8DEE9
# color0  #3B4252
# color1  #BF616A
# color2  #A3BE8C
# color3  #EBCB8B
# color4  #81A1C1
# color5  #B48EAD
# color6  #88C0D0
# color7  #E5E9F0
# color8  #4C566A
# color9  #BF616A
# color10 #A3BE8C
# color11 #EBCB8B
# color12 #81A1C1
# color13 #B48EAD
# color14 #8FBCBB
# color15 #ECEFF4

# Keyboard bindings
map ctrl+v paste_from_clipboard
map ctrl+c copy_or_interrupt
# map ctrl+shift+c copy_to_clipboard
map ctrl+shift+f launch --type=overlay kitty +kitten icat
map shift+page_up   scroll_page_up
map shift+page_down scroll_page_down
map shift+home      scroll_home
map shift+end       scroll_end
map ctrl+0          change_font_size all 0

# Middle click paste from primary selection
mouse_map middle release ungrabbed paste_from_selection
# selection_foreground        none
# selection_background        none
include themes/noctalia.conf




# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
