title = ${filename/no-ext}
watch-later-options-remove=sub-pos
# keepaspect-window=no
geometry=1920x1080
fs
osc=no
osd-bar=no
osd-font=Inter Medium
osd-font-size=15
osd-color='#ffffff'
osd-border-size=0
osd-shadow-color="#000000"
osd-bar-h=2
osd-bar-w=50
osd-margin-y=20
osd-bar-align-y=0.7
osd-shadow-offset=1
sub-font=Inter
audio-file-auto=exact
sub-file-paths=Sub:sub:Subs:subs:Subtitle:subtitle:Subtitles:subtitles:Ru sub:ru sub:Ru subs:ru subs:Rus sub:rus sub:Rus subs:rus subs:rusubs:russubs:rusub:субтитры:сабы
load-scripts=no
scripts="~~/scripts/material-osc.lua:~~/scripts/thumbfast.lua:~~/scripts/persist-properties.lua"
keep-open=yes
border=no
sub-auto=fuzzy
gpu-context=wayland
# hwdec=auto-safe
deband=yes 
demuxer-mkv-subtitle-preroll=yes 

[Anime]
fs
save-position-on-quit
scripts="~~/scripts/material-osc.lua:~~/scripts/thumbfast.lua:~~/scripts/persist-properties.lua:~~/scripts/sub-select.lua:~~/scripts/trashfileonend.lua"
glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"

[Film]
fs
save-position-on-quit
scripts="~~/scripts/material-osc.lua:~~/scripts/thumbfast.lua:~~/scripts/persist-properties.lua:~~/scripts/sub-select.lua:~~/scripts/trashfileonend.lua"
# profile=gpu-hq
