[main]
include=~/.config/foot/themes/noctalia
pad=25x25
#font=SFMono Nerd Font Mono:size=11.5:weight=150
font=JetBrainsMono Nerd Font:size=11.4:weight=150
selection-target=clipboard
[scrollback]
lines=10000

[url]
style=curly

[cursor]
style=underline
underline-thickness=2
blink=yes
blink-rate=500

[mouse]
hide-when-typing=yes

[colors-light]
alpha=0.75
flash-alpha=0.75
blur=yes

[colors-dark]
alpha=0.75
flash-alpha=0.75
blur=yes

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
scrollback-home=Shift+Home
scrollback-end=Shift+End
font-reset=Control+0
clipboard-paste=Control+Shift+v Control+v
