hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("noOvershot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.curve("niri", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("horizontalView", { type = "spring", mass = 1, stiffness = 800, dampening = 67 })
hl.curve("openSpring", { type = "spring", mass = 1, stiffness = 450, dampening = 50 })
hl.curve("closeSpring", { type = "spring", mass = 1, stiffness = 600, dampening = 50 })
hl.curve("openLayerSpring", { type = "spring", mass = 1, stiffness = 500, dampening = 50 })
hl.curve("closeLayerSpring", { type = "spring", mass = 1, stiffness = 500, dampening = 50 })
-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 1, spring = "horizontalView" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 1, spring = "openSpring", style = "popin 30%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1, spring = "closeSpring", style = "popin 80%" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "quick" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 3, bezier = "quick" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 3, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 2.5, bezier = "noOvershot", style = "popin" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.5, spring = "openLayerSpring", style = "popin 60%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2.5, spring = "closeLayerSpring", style = "popin 80%" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1, spring = "horizontalView", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 4, bezier = "quick" })
hl.animation({ leaf = "monitorAdded", enabled = true, speed = 4, bezier = "quick" })
