#!/bin/bash
DSCP_VALUE="61"
SLICE_NAME="xkeen.slice"
TABLE_NAME="dscp-$DSCP_VALUE"
SLICE_UNIT="$HOME/.config/systemd/user/$SLICE_NAME"

if [ ! -f "$SLICE_UNIT" ]; then
  mkdir -p "${SLICE_UNIT%/*}"
  cat >"$SLICE_UNIT" <<EOF
[Unit]
Description=XKeen DSCP $DSCP_VALUE

[Slice]
MemoryAccounting=yes

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now "$SLICE_NAME"
fi

if ! sudo nft list table inet "$TABLE_NAME" &>/dev/null; then
  systemctl --user start "$SLICE_NAME"
  SLICE_PATH=$(systemctl --user show "$SLICE_NAME" -P ControlGroup)
  SLICE_PATH=${SLICE_PATH#/}

  [ -z "$SLICE_PATH" ] && {
    echo "SLICE_PATH пуст"
    exit 1
  }

  sudo nft -f - <<EOF
table inet $TABLE_NAME {
    chain output {
        type filter hook output priority mangle; policy accept;
        socket cgroupv2 level 4 "$SLICE_PATH" ip dscp set $DSCP_VALUE
    }
}
EOF
fi

exec systemd-run --user --scope -p Slice="$SLICE_NAME" -- "$@"
